version: "3.6"
### networks
networks:
  minecraft:
    name: minecraft
services:
  mc:
    image: itzg/minecraft-server
    container_name: docker_mc_1
    ports:
      - 6969:25565
      - 19132:19132/udp
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      VERSION: 1.19
      ICON: https://new.intellidnd.com/assets/images/primary-icon.png
      MOTD: "The MC MC MC server"
      ONLINE_MODE: "FALSE"
    volumes:
      - ./docker/minecraft:/data
    tty: true
    stdin_open: true
    restart: always
    networks:
      - minecraft
  server:
    build: .
    command: python3.9 server.py --debug --port 80 --host 0.0.0.0
    networks:
      - minecraft
    ports:
      - 4343:80
    environment:
      - PORT=80
      - MOOJCRAFT_APP_ID=${MOOJCRAFT_APP_ID}
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - MOOJCRAFT_PUBLIC_KEY=${MOOJCRAFT_PUBLIC_KEY}
      - DISCORD_SERVER_ID=${DISCORD_SERVER_ID}
      - MOOJIG_DISCORD_USER_ID=${MOOJIG_DISCORD_USER_ID}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/app
    restart: always
