import os

MOOJCRAFT_APP_ID = os.environ.get("MOOJCRAFT_APP_ID")
DISCORD_BOT_TOKEN = os.environ.get("DISCORD_BOT_TOKEN")
MOOJCRAFT_PUBLIC_KEY = os.environ.get("MOOJCRAFT_PUBLIC_KEY")
DISCORD_SERVER_ID = os.environ.get("DISCORD_SERVER_ID")
MOOJIG_DISCORD_USER_ID = os.environ.get("MOOJIG_DISCORD_USER_ID")
DISCORD_WEBHOOK_URL = os.environ.get("DISCORD_WEBHOOK_URL")
