# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: alpine:3.14
    steps:
      - checkout
      - run:
          name: Setup Docker CLI
          command: apk add --update docker-cli openrc openssh
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            echo 'Starting build...'
            docker login dr.chimid.rocks -u moojig -p $DOCKERHUB_PASSWORD
            docker build --pull --rm -f "Dockerfile" -t dr.chimid.rocks/mcmc:latest "."
      - run:
          name: Push Docker Image
          command: |
            echo 'Pushing to dr.chimid.rocks...'
            docker push dr.chimid.rocks/mcmc:latest
      - add_ssh_keys:
          fingerprints:
            - "ff:23:b8:4a:24:2c:03:3d:22:66:d4:16:2e:32:07:cf"
      - run:
          name: chmod
          command: chmod 700 $HOME/.ssh/*
      - run:
          name: Run update_mcmc script over SSH
          command: |
            echo 'Connecting to $DOCKERHOST and running script...'
            ssh -o "StrictHostKeyChecking=no" $DOCKERHOST $REMOTE_USER/docker/update_mcmc.sh
            echo 'All done! mcmc.chimid.rocks now deployed!'
  runner-test:
    machine: true
    resource_class: moojigc/rocks_ci
    steps:
      - run: echo "Hi I'm on Runners!"
workflows:
  build:
    jobs:
      - runner-test:
          filters:
            branches:
              only:
                - runner-test
      - build:
          filters:
            branches:
              only:
                - main
