# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    machine: true
    resource_class: moojigc/rocks_ci
    # docker:
    #   - image: alpine:3.14
    steps:
      - checkout
      # - run:
      #     name: Setup Docker CLI
      #     command: apk add --update docker-cli openrc openssh
      # - setup_remote_docker:
      #     version: 20.10.14
      #     docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            echo 'Starting build...'
            sudo docker login $DOCKERHUB_HOST -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
            sudo docker build . -t $DOCKERHUB_HOST/mcmc:latest "."
      - run:
          name: Push Docker Image
          command: |
            echo 'Pushing to $DOCKERHUB_HOST...'
            sudo docker push $DOCKERHUB_HOST/mcmc:latest
      - run:
          name: Run webhook
          command: |
            curl --location --request POST $WEBHOOK_URL \
            --header 'X-Webhook-Password: '$WEBHOOK_PASS'' \
            --header 'Content-Type: application/json' \
            --data-raw '{
                "container": "mcmc",
                "image": "mcmc:latest",
                "stack": "mcmc"
            }'
            echo 'All done! mcmc.chimid.rocks now deployed!'
  # runner-test:
  #   machine: true
  #   resource_class: moojigc/rocks_ci
  #   steps:
  #     - run: echo "Hi I'm on Runners!"
workflows:
  build:
    jobs:
      # - runner-test:
      #     filters:
      #       branches:
      #         only:
      #           - runner-test
      - build:
          filters:
            branches:
              only:
                - main
